### ISSUE TITLE
Change Circle Size

### ISSUE THREAD

**Issue by pinkp** [codrops/AnimatedCustomCursor#1]
Love this, its amazing! 
Just wondering how to make it smaller? I'm using demo 3. I've been looking through the code but can't see a simple solution. Thanks

**Comment by botelho** [comment]
First, you need to change the values of the SVG width/height and viewbox. Also the cx/cy (half of what's set for the width/height) and radius parameters of the circle inside the SVG. 
```
<svg class="cursor" width="280" height="280" viewBox="0 0 280 280">
	<defs>
		<filter id="filter-1" x="-50%" y="-50%" width="200%" height="200%" 
		filterUnits="objectBoundingBox">
			<feTurbulence type="fractalNoise" baseFrequency="0.02 0.15" numOctaves="3" result="warp" />
			<feDisplacementMap xChannelSelector="R" yChannelSelector="G" scale="0" in="SourceGraphic" in2="warp" />
		</filter>
	</defs>
	<circle class="cursor__inner" cx="140" cy="140" r="50"/>
</svg>
```
Then in cursor3.js you need to update the radius too. On line 34, 
```
radius: {previous: 50, current: 50, amt: 0.14}
```
change 50 to the new radius value and on line 88 and 92
```
this.renderedStyles['radius'].current = 120;

...

this.renderedStyles['radius'].current = 50;
```
change the from/to values for the radius when hovering an element.
Hope it helps!
