### ISSUE TITLE
cursor disappear on longer website

### ISSUE THREAD

**Issue by naumstudio** [codrops/AnimatedCustomCursor#2]
We have a problem that cursor works only on the place of the size of the screen (2880x1440.. just first visible screen on website) but when your website is scrollable and much longer - when you scroll, cursor disappear. This issue is also in your version on Codrops.

Is it a bug or just a bad implementation? :) 
Thanks for the solution!

**Comment by botelho** [comment]
Yes, it's a bug, we'll need to update it. Since this was implemented on a non scrollable layout, we didn't consider the current scroll value. Thanks for pointing that out.
