### ISSUE TITLE
Issue regarding scrolling + little typo

### ISSUE THREAD

**Issue by DamChtlv** [codrops/AnimatedCustomCursor#7]
There is an unnecessary use of scroll data in this code
*(at the moment, if you scroll the cursor goes up at some point and disappear)*.

--- 

[cursor.js]( https://github.com/codrops/AnimatedCustomCursor/blob/e5e0b86429f14e0ac37628b4a9bec35fca0b81f7/src/js/cursor.js#L47)

Before:
```js
this.renderedStyles.ty.previous = this.renderedStyles.ty.previous = mouse.y - this.bounds.height/2 - docYScroll;
```

After:
```js
this.renderedStyles.ty.previous = this.renderedStyles.ty.current = mouse.y - this.bounds.height/2;
```
--- 

[cursor.js]( https://github.com/codrops/AnimatedCustomCursor/blob/e5e0b86429f14e0ac37628b4a9bec35fca0b81f7/src/js/cursor.js#L56)

Before:
```js
this.renderedStyles['ty'].current = mouse.y - this.bounds.height/2 - docYScroll;
```

After:
```js
this.renderedStyles['ty'].current = mouse.y - this.bounds.height/2;
```

---

Also a little typo here *(`previous` used twice, should be `current`)*:
[cursor.js]( https://github.com/codrops/AnimatedCustomCursor/blob/e5e0b86429f14e0ac37628b4a9bec35fca0b81f7/src/js/cursor.js#L47)

After:
```js
this.renderedStyles.ty.previous = this.renderedStyles.ty.current = mouse.y - this.bounds.height/2;
```

**Comment by botelho** [comment]
Thank you so much!
